name = "LazyGrids"
uuid = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
authors = ["Sheehan Olver <s.olver@imperial.ac.uk>", "Jeff Fessler <fessler@umich.edu>"]
version = "0.2.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.6"
