name = "LazyGrids"
uuid = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
authors = ["Sheehan Olver <s.olver@imperial.ac.uk>", "Jeff Fessler <fessler@umich.edu>"]
version = "0.1.0"

[deps]
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"

[compat]
LazyArrays = "0.21"
julia = "1.6"
